### ISSUE TITLE
I hope next time it's easier!

### ISSUE THREAD

**Issue by alcardini** [zarquon42b/VILDS#1]
After 10 minutes of logging in, selecting spiral galaxies etc., I might have made it and hope it will be easier next time or I'll go back to plain emails (I'm old, Stefan!).

"we could rerun the SLIDR2 with the bootstrapped data over and over again and compare outcomes"
We have to run it in the previous step, the statistical model (e.g., the regression). It is certainly doable and whatever works best for you it's fine for me.

**Comment by zarquon42b** [comment]
Hi Andrea,
thank you for joining me here. Development will be much more consistent and efficient here - believe me ;)
> I'm old, Stefan!

That is not a thing Andrea but the road to ruin. To quote Lemmy: "_If you think you are too old to rock 'n roll, then you are._"
So do not think that.
