### ISSUE TITLE
Add magnification for visualization of between group differences

### ISSUE THREAD

**Issue by alcardini** [zarquon42b/VILDS#10]
![Screenshot_20220727_181050](https://user-images.githubusercontent.com/105369234/181296943-c7484300-a538-49dc-abeb-4969dae094d6.jpg)
I am not sure if you can see the screenshot I (should have) attached. I wonder whether we (i.e., you!) can mix the two types of plots: magnified grids with displacement vectors (MJ) plus ILDS.

Cheers
Andrea

**Comment by zarquon42b** [comment]
So you want the lollipop graphs being added? 
Because you can control the grid with ngrid (the higher ngrid-values, the finer the wiremesh resolution)

**Comment by alcardini** [comment]
If not too difficult to do, I'd like lollipops + magnified differences: it helps to check that ILDs are picking up changes that one (kind of) sees also with the grids.
Thanks!

**Comment by zarquon42b** [comment]
Hi Andrea, the lollipops are no problem. But the magnifying thing raises some questions:

- Do you only want to exaggerate only the grid or also the actual landmark configs (leading to longer lollipop sticks)?
- Do we want a distortion by dragging both reference and target further from the mean by the same amount or only the target away from the reference?
- What is that amount supposed to be? - e.g. a scalefactor where 1 would be the current situation.

**Comment by alcardini** [comment]
Hi Stefan,
I'd tend to say (but would like you to check if it's reasonable):
1) I would magnify everything as in MorphoJ or Morpheus.
2) I am not sure about this: MJ starts from the mean, TPSRelw does the same and also Morphologika; Morpheus let you choose. I wonder if the mean is the best option. For groups, one knows it is halfway between the target and ref. (so that if one wants the magnification from the ref. he/she just double the magnification from the mean). For allometry, the mean is still reasonable and I guess that the magnification (x1.5,x2,x2.5 etc.) should be relative to the endpoints of the regression line (i.e., the predicted shape of the biggest individual, if that's the target, or the smallest if one uses the opposite extreme as the target). Do you agree?
3) Morpheus is still the best software I know for this and Dennis used as magnification factors: 1.2; 1.4; etc. up to 1.8; then, 2; 3; 4 etc.

You may have better ideas. I am very open and this (above) reflects probably what I am used to have in other programs.
Cheers

Andrea

**Comment by zarquon42b** [comment]
Hi Andrea,
unfortunately, I haven't used MJ and Morpheus for more than a decade. However, just using words like "magnification" which appear in the software UI are not well defined. Generally, we are talking about a reference and a target configuration. So what I could do is to symmetrically increase the distance between those shapes by dragging them further away from their common mean and then plot it. I will push a draft version for you to play around later this day or tomorrow morning.

**Comment by alcardini** [comment]
You're right. It's poor defined and magnification is used inconsistently (by me too!). However, what you describe is exactly what I suggest. It should work also for allometry as our ref. and target are already the opposite extremes of the trajectory. The only doubt I have (a tiny difference if any) is that the mid-point between the smallest and largest predicted shape may not be 100% identical to the sample mean shape (through which, if i am correct, the regression line goes). I have the suspicion that the sample mean would be better.
With groups, it's different: the midpoint of the mean of A and the mean of B is exactly what one is interested in and it's the zero point in the BG-PCA space, which 'is the trajectory' of mean group differences.

Thanks for adding the magnification.

**Comment by zarquon42b** [comment]
Hi Andrea please  test

**Comment by alcardini** [comment]
I am getting the new version now. I have another issue to open (separate message).

**Comment by alcardini** [comment]
I think the new version has the help file broken:
![Screenshot_20220728_122712](https://user-images.githubusercontent.com/105369234/181484283-38a30dda-d1d3-4749-9353-f1df42768f81.jpg)

**Comment by zarquon42b** [comment]
No Andrea, this happens when the old version cannot be cleanly reloaded. Just restart Rstudio.

**Comment by alcardini** [comment]
OK!

**Comment by alcardini** [comment]
It was already the latest VILDS
devtools::install_github("zarquon42b/VILDS")
Skipping install of 'VILDS' from a github remote, the SHA1 (af209443) has not changed since last install.
  Use `force = TRUE` to force installation
