### ISSUE TITLE
Clarify behaviour for ref=TRUE/FALSE

### ISSUE THREAD

**Issue by alcardini** [zarquon42b/VILDS#11]
This is something I am not sure I am getting right:
 ref	ref logical: if TRUE, the reference shape defined in ILDSR2 will be plotted. Otherwise the target is used.
Is it simply to decide which shape is shown in the plot (target from ref. or viceversa)?

If so, please look at the two screenshot: same analysis but one is ref=FALSE and the other TRUE: shouldn't they show the same supported ILDs? Why the 'long nose' if ref=TRUE is coded red (contraction) whereas it's an expansion?
Surely I get something wrong.

![ref to target](https://user-images.githubusercontent.com/105369234/181482614-103c4d2c-33b4-4d31-a57f-7ca119049511.jpg)
![target to ref](https://user-images.githubusercontent.com/105369234/181482621-0865aac4-50fe-4d88-beaa-2047b85e81c8.jpg)

**Comment by zarquon42b** [comment]
If ref=TRUE, the displacement will be from reference to target and the otherway round if ref=F.
I do not get this weird result. Are you using the  latest version of VILDS?
However, when inverting ref and target, should we also invert the visualization of expansion and contraction (which is easily done by using the inverse of the ratio)?

BTW if you don't want links, set links=NULL (not FALSE).

![R Graphics: Device 2 (ACTIVE)_002](https://user-images.githubusercontent.com/1515863/181485464-4f3beb4b-292f-4582-aca4-6e49819c9de0.png)
![R Graphics: Device 2 (ACTIVE)_003](https://user-images.githubusercontent.com/1515863/181485485-e1d345b5-a340-4312-8011-7e59e3fb0009.png)


First pic: ref=T, second pic: ref=F

**Comment by alcardini** [comment]
Yes, it's the latest version. Reinstalled after you told me to try the magnification.
I kind of see where the problem might be and possibly inverting the ratios will suffice. Alternatively, one could forse users to swap the order of the groups before doing the analysis, if one wants to see the other group.

With ref=TRUE it seems to me that also the wireframe and grid should become those of the ref. (whereas now they're still showing the target, if I am correct - see below).

![Screenshot_20220728_125944](https://user-images.githubusercontent.com/105369234/181490152-3cb3d639-44cf-4675-a332-04662c899b28.jpg)

**Comment by zarquon42b** [comment]
Hi Andrea, is this the latest version? Because I just implemented this a couple of minutes ago. Did you update already?

**Comment by zarquon42b** [comment]
Also can you please send me your example data, so I can reproduce what you are doing.
> Alternatively, one could forse users to swap the order of the groups before doing the analysis, if one wants to see the other group.

The order of the groups is determined by their labels, so not a good idea. The result in the visualization is the same as swapping the target and reference.

**Comment by zarquon42b** [comment]
Is this also the latest version of Morpho from github? This will be needed for the correct display of the 2D cases.

**Comment by alcardini** [comment]
Possibly it's not the latest Morpho: the installation from terminal (unlike Rstudio) does not ask me to update dependencies.
Well, in fact, it seems it is, as I get this:
devtools::install_github("zarquon42b/Morpho")
Skipping install of 'Morpho' from a github remote, the SHA1 (1f50fbd3) has not changed since last install.
  Use `force = TRUE` to force installation

Trying te magnification, I get different ILDs coloured when it's 1 or 2 (same analysis, just different magnification). And the wireframe is still on the non-magnified target.

![Screenshot_20220728_131357](https://user-images.githubusercontent.com/105369234/181493113-df219bb7-cb8e-4571-955e-6e7ba42f6130.jpg)
![Screenshot_20220728_131404](https://user-images.githubusercontent.com/105369234/181493117-e0a0ebb4-8140-496a-8f77-9799feff0737.jpg)

**Comment by alcardini** [comment]
Data! I missed that. It's the same I sent you before. Right now I am playing with the Pinocchio simulated data (below).
[pinocchio1.txt](https://github.com/zarquon42b/VILDS/files/9208803/pinocchio1.txt)
[pinocchio2.txt](https://github.com/zarquon42b/VILDS/files/9208804/pinocchio2.txt)
.

**Comment by zarquon42b** [comment]
EDIT: my mistake

**Comment by zarquon42b** [comment]
Here is what I get for pinocchio1.txt - I do not find any inconsistencies.

```
mydata <- read.table("~/Desktop/pinocchio1.txt",header = T)
pino1 <- vecx(as.matrix(mydata[,-c(1:2)]),byrow = T,revert = T,lmdim = 2)
proc <- procSym(pino1)
ilds <- ILDSR2(proc$rotated,factor(mydata$group),plot=FALSE,bg.rounds=0,wg.rounds=99)
## gives a very low confidence so we have to lower the conftol values to have the ILDs plotted.
visualise(ilds,magnify=2,conftol=c(70,30))
visualise(ilds,magnify=1,conftol=c(70,30))
visualise(ilds,magnify=1,ref=FALSE,conftol=c(70,30))
```
And here are the outputs:
![magnify2](https://user-images.githubusercontent.com/1515863/181496681-0cf8b53c-605d-4f5f-8fbb-c915d985e2fe.png)
![magnify1](https://user-images.githubusercontent.com/1515863/181496662-5a6418ea-00ee-413c-9ae2-1242338330bb.png)
![magnify1refFALSE](https://user-images.githubusercontent.com/1515863/181496672-b59a5712-de0b-4e2f-a8f4-6a93a96df175.png)

**Comment by zarquon42b** [comment]
I just fixed that long lollipops at the border get truncated. They now get displayed correctly:
EDIT: you can also see on this and the last post, that contraction/expansion gets plotted and interpreted correctly.
![magnify1refFALSE](https://user-images.githubusercontent.com/1515863/181497910-60e7acde-c468-4549-86c4-0eabb78f3430.png)
.

**Comment by alcardini** [comment]
Answering by email with an mkv video attached.

**Comment by alcardini** [comment]
Now selected (coloured) ILDS are consistent if I swap ref. and target: perfect. However, they should be on the tips of the lollipops with the wireframe also linking those tips: otherwise one is easily mislead as a contraction (red in the screenshot below) is shown with lines that suggest an expansion. Not sure if I explained myself well ...

![Screenshot_20220728_141532](https://user-images.githubusercontent.com/105369234/181502675-3d0670e7-1d76-457b-9a8d-ff0b3c2c940f.jpg)

**Comment by zarquon42b** [comment]
No it is a contraction: if you look at the end of the lollipops of 5 and 2, then you can see that the distance decreases between both shapes => contraction.

**Comment by zarquon42b** [comment]
Putting this on the end of the lollipops would make the code much more complicated because for lollipop=FALSE, those have to be attached to the other config. I find it more comprehensible this way, actually.

EDIT: the way I understand contraction/expansion is: when I want to go from my current reference to my target, I need to expand/contract ILDS.

**Comment by zarquon42b** [comment]
Here is the output of a little loop. Using magnify values < 0 gives now the same behaviour as ref=FALSE as it actually switches the direction.
```
myseq <- seq(from=-2,to=2,length.out = 10)
for (i in 1:10) {
    png(paste0("~/Desktop/movie/movie",sprintf("%02d.png",i)))
    visualise(ilds,magnify=myseq[i],ref=FALSE,conftol=c(70,30))
    dev.off()
    }
```

[movie.webm](https://user-images.githubusercontent.com/1515863/181507193-414e7b6a-4f69-4ffc-97e7-2b25f10f5574.webm)

**Comment by alcardini** [comment]
I suspected the code was more difficult because Chris (in MJ) shows either the wireframe OR the lollipops/grids. Never both in the same plot.
The way it is now is very counterintuitive for me. I wrote "a contraction (red in the screenshot below) is shown with lines that suggest an expansion": NB it's the LINES that are misleading; not the colour. LONG LINES (suggesting expansion) when it's red (lollipops, grids and colour coding). 

For the wireframe, the solution is Chris' approach: don't show it if one is using grids/lollipops. However, if colour coded ILDS are not shown at the tips of the lollipops, they'll be misleading.
Want to talk about it in a videocall?

**Comment by zarquon42b** [comment]
It makes coding difficult because it is algorithmically less consistent (IMHO). By defining a reference and a target  everything will have to be interpreted within that frame: **from** => **to**. So an expansion means that a line will expand when going from reference to target.
So here is the underlying rationale:

- What you see on the plot is a reference shape and how the landmarks are connected with links
- The lines that expand/contract when moving **from** the reference **to** the target are colored accordingly
- To visualize the global deformation a TPS-grid (**from** => **to**) is displayed
- To visualize where the target actually is in relation to the reference, we use the lollipops


The thing is that it appears that you are already very preoccupied by your previous usage of other software. I had the same issue when coming from MJ and started developing Morpho and decided that it stands in the way more often than not.

**Comment by alcardini** [comment]
The software I used is irrelevant. I use Morpheus as an examples because it allows me to show you how I wish to display that output.
I am not arguing about the algorithm. I fully trust you on that and have nothing to say about.
The fact is, and this is not about what software one is used to, that we call contraction something that we show using ILDs longer than they are in the splined reference (magnified target, if you prefer). Try asking a naive user if he/she finds this intuitive.

You're doing an amazing work with the coding, Stefan. I am not asking you to code something either difficult or that is a violation of the rationale behind the coding. 
The way it is now is confusing to me and I suspect most users. 

Less crucial but also a bit confusing, and here what people are used to matters, as all other programs do it that way: the grey wireframe, I believe, is the mid-point between ref. and target; because of that, lollipops go in two directions but they should be displacement vectors going from a start to an end shape. I guess this is a consequence of my suggestion of using the grand mean of the two means as the origin of the lollipops. Shall we fix this by using, instead, the observed ref. shape (group 1 means)? As long as this is clear in the help, it's OK I believe.
For the other issue, I am not sure what to suggest. Maybe we go back to the original version with no magnification and no lollipops.

All those requests were not just to make the visualization nicer (and bother you with more coding!). They do help me to check if selected ILDS help with the interpretation when shown together with conventional visualizations (wireframes, grids and vectors). But they're not essential.

**Comment by zarquon42b** [comment]
I thought about this issue: what about that we display the highlighted ILDS for the target if lollipop=T and use the reference otherwise.
Here is what it looks like for `lollipop=TRUE`
![R Graphics: Device 2 (ACTIVE)_100](https://user-images.githubusercontent.com/1515863/181727027-f2b8fe0e-0ac9-43a7-9e36-af47a492e50c.png)

... and  `lollipop=FALSE`
![R Graphics: Device 2 (ACTIVE)_101](https://user-images.githubusercontent.com/1515863/181727227-f3f0c063-d9ff-4a2c-8517-567b1824f991.png)

**Comment by zarquon42b** [comment]
The resulting video from pinocchio 1 would then look like this (click to play):

[test.webm](https://user-images.githubusercontent.com/1515863/181728868-f58bb3dd-4d94-482e-a4e9-1dd049c77329.webm)
