### ISSUE TITLE
parameters for links, grid etc.

### ISSUE THREAD

**Issue by alcardini** [zarquon42b/VILDS#14]
This is somewhere in the help but can't see it now: how do I change, say, colour and thickness of a wireframe (or grid or ILD)?
Thanks

Andrea

**Comment by zarquon42b** [comment]
It's all in the docs:
The links are modelled to be 2/3 of the width of the relevant ILDS. All is controlled by lwd. Just play around a bit.

![Selection_135](https://user-images.githubusercontent.com/1515863/182125349-492f7223-4707-44de-8663-17a8087d126f.png)

**Comment by alcardini** [comment]
OK for the relative thickness of relevant ILDS and wireframe. Yet, I can't see how to make, for instance, black grids, lightgrey wireframe and green lollipops. Probably it's there before my eyes ... but can't see it and have little experience with graphical parameters.

**Comment by zarquon42b** [comment]
No, I have not yet put all in the options, as I wanted to nail down the functionality first. Also having a lot of parameters is very confusing. Can you please provide an explicit list containing which options you would want to have included.

**Comment by alcardini** [comment]
Changing colours and thickness of lines (any of them) might be good but you're right it might be also confuse.
I'd like the VILDS-specific output (i.e., relevant links) to be well emphasized. This is already the case. For the wireframe, grids and lollipops, they should be somewhat in the background (de-emphasized) as an aid which does not dominate the plot. Light grey is good but if we do everything light grey it's becomes confusing. I wonder if a dashed light grey grid with a darker grey (like now more or less) wireframe helps. For the lollipops, I am not sure how to code them: dotted black with thin lines?

**Comment by zarquon42b** [comment]
OK, the thing is that the dotted lines will only work in the 2D case as there is no 3D equivalent present. 

- Did we agree to make the lollipops mandatory or optional?
- I will make the tps grid a bit lighter and the wireframe a bit darker.

**Comment by alcardini** [comment]
Hi Stefan,
thanks for the update. Answers below.
Cheers
Andrea

>OK, the thing is that the dotted lines will only work in the 2D case as there is no 3D equivalent present.
Fine for me.

>    Did we agree to make the lollipops mandatory or optional?
Optional but default? 

>    I will make the tps grid a bit lighter and the wireframe a bit darker.
Sounds good to me.

**Comment by zarquon42b** [comment]
I added a lot of additional options. Please test and report back.
**Please install latest Morpho from github first as I had to adapt some functions to allow for this to work.**

**Comment by alcardini** [comment]
I'll do my best, Stefan.
Today I am stuck with something, but between today and tomorrow I hope to play a bit more with VILDS. From Friday I am on holiday and from Saturday totally offline for two weeks.
When I come back, I hope to work with more continuity.

Many thanks for all the changes and the improvements.
Cheers

Andrea
