### ISSUE TITLE
plot ilds

### ISSUE THREAD

**Issue by alcardini** [zarquon42b/VILDS#3]
I tried:
require(Morpho)
data(boneData)
proc <- procSym(boneLM)
groups <- name2factor(boneLM,which=3)
reference <- arrMean3(proc$rotated[,,groups=="ch"])
target <- arrMean3(proc$rotated[,,groups=="eu"])
ilds <- ILDSR2(proc$rotated,groups,reference,target,plot=TRUE)
plot(ilds) # NOTHING IS PLOTTED
plot.ILDSR2(ilds) # GET MESSAGE: Error in plot.ILDSR2(ilds) : could not find function "plot.ILDSR2"

Am I missing something?
Cheers A

**Comment by zarquon42b** [comment]
> plot(ilds) # NOTHING IS PLOTTED

This should open an rgl 3d window to plot the 3d wireframe
![RGL device 1  Focus _001](https://user-images.githubusercontent.com/1515863/168340433-90f1c2dc-1526-4f19-aff1-71a13968aefc.png)
Works like charm here.

**Comment by zarquon42b** [comment]
Works on other machines as well. I guess you are using Rstudio. It opens the rgl window rather ashamed and silently behind the main window. Please check.
