### ISSUE TITLE
not testing but just given a quick try and got error mess.

### ISSUE THREAD

**Issue by alcardini** [zarquon42b/VILDS#7]
Hi Stefan,
today and I fear until next week, when I am finally done with lectures, I'm unlikely to be able to properly play with the function. I definitely need to understand better the clustering thing.

For now I only run your example and one with my data. In both cases I got the error message below:
Error in FUN(newX[, i], ...) : unused argument (simplify = FALSE)
Things seem to work but the rgl visualization only shows the landmarks, without the 'important' ILDs emphasized (i.e., only dots and no lLD line).

I've noticed that when I reinstalled VILDS, it asked to update Morpho. If I am correct, it does it from the github depository and thus is the latest version (not the one on CRAN).

Thanks for all the amazing work. I am sorry not to be able to keep your pace. I hope to do more next week. Anyway, for anything you want me to check urgently, do drop me an email.
Cheers

Andrea

**Comment by zarquon42b** [comment]
Maybe I accidentally had pushed a flawed state but it works nicely here.

> I've noticed that when I reinstalled VILDS, it asked to update Morpho. If I am correct, it does it from the github depository and thus is the latest version (not the one on CRAN).

No, this means you have an old version of Morpho installed. But please install the latest Morpho snapshot via `devtools::install_github("zarquon42b/Morpho")`

**Comment by zarquon42b** [comment]
I added a new option called `gap` . If `TRUE`, the clustering is performed by looking for gaps in the univariate R2 distributions. It is simply but in my use cases more robust. If FALSE as clustering is performed.
Now even in the non-symmetrized data, I get a sensible output.
